### ISSUE TITLE
How to make Item/ID column more smaller ?

### ISSUE THREAD

**Issue by akmalshukri** [shabyWoks/DynamicTableLayout#1]
Thanks for your app .. It very good .. I download it and want make item/ID column more smaller ? when i make it smaller then screen width not full match ..

**Comment by shabyWoks** [comment]
Hi akmal, replace 'SCREEN_WIDTH/5' with any value smaller than it every where in the code, and similarly 'SCREEN_HEIGHT/20' with any value smaller than it every where in the code. Try this i think it should work.
